# Site settings
title: JY Tech Blog
email: thinkpiece@yahoo.com
description: > # this means to ignore newlines until "baseurl:"
  Hello, I'm JY, postdoctoral researcher at KAIST in Korea.
  Majored in the Electrical Engineering and currently interested in
  machine learning, deep learning, computer vision, and their corresponding
  hardware architectures.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.jyp.me" # the base hostname & protocol for your site
twitter_username: jparktweet
github_username:  thinkpiece

# Build settings
markdown: kramdown
