# Site settings
title: JY Tech Blog
email: thinkpiece@yahoo.com
description: > # this means to ignore newlines until "baseurl:"
  Some thoughts on machine learning software and hardware design.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.jyp.me" # the base hostname & protocol for your site
twitter_username: jparktweet
github_username:  thinkpiece

# Build settings
markdown: kramdown
